# Generated by Django 4.2.7 on 2023-11-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="availability",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="base_caliber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bezel_material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="brand",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Rolex", "Rolex"),
                    ("Omega", "Omega"),
                    ("Seiko", "Seiko"),
                    ("Casio", "Casio"),
                    ("Timex", "Timex"),
                    ("Glashutte", "Glashutte"),
                    ("Patek Philippe", "Patek Philippe"),
                    ("Audemars Piguet", "Audemars Piguet"),
                    ("Girard Perragaux", "Girard Perragaux"),
                    ("Jaeger LeCoultre", "Jaeger LeCoultre"),
                    ("IWC", "IWC"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_diameter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp_material",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Good", "Good"),
                    ("Very Good", "Very Good"),
                    ("New", "New"),
                    ("Unknown", "Unknown"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="crystal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dealer_product_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial_numerals",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="frequency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="functions",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="image",
            field=models.ImageField(
                blank=True,
                default="watches/images/placeholder.png",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="watch",
            name="listing_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="lug_width",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="model",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement_caliber",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="number_of_jewels",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="power_reserve",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="scope_of_delivery",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="thickness",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="water_resistance",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="year_of_production",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
