# Generated by Django 4.2.7 on 2023-11-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_watch_availability_alter_watch_base_caliber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="availability",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="base_caliber",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bezel_material",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_color",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_material",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="brand",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_diameter",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_material",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp_material",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="condition",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="crystal",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dealer_product_code",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial_numerals",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="frequency",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="functions",
            field=models.TextField(default="not available"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="gender",
            field=models.CharField(default="not available", max_length=50),
        ),
        migrations.AlterField(
            model_name="watch",
            name="listing_code",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="location",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="lug_width",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="model",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement_caliber",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="number_of_jewels",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="power_reserve",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="price",
            field=models.FloatField(default="not available"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="reference_number",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="scope_of_delivery",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="thickness",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="title",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="water_resistance",
            field=models.CharField(default="not available", max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="year",
            field=models.IntegerField(default="not available"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="year_of_production",
            field=models.IntegerField(default="not available"),
        ),
    ]
