# Generated by Django 4.2.7 on 2023-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_watch_availability_alter_watch_base_caliber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="description",
            field=models.TextField(default="not available"),
        ),
        migrations.AlterField(
            model_name="watch",
            name="price",
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name="watch",
            name="year",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="watch",
            name="year_of_production",
            field=models.IntegerField(default=None),
        ),
    ]
