# Generated by Django 4.2.7 on 2023-11-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_watch_description_alter_watch_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="price",
            field=models.FloatField(default=None, null=True),
        ),
    ]
