# Generated by Django 4.2.7 on 2023-11-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_watch_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watch",
            name="year",
        ),
        migrations.AlterField(
            model_name="watch",
            name="year_of_production",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
