# Generated by Django 4.2.7 on 2023-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_watch_options_alter_watch_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="functions",
            field=models.TextField(blank=True),
        ),
    ]
