# Generated by Django 4.2.7 on 2023-11-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_watch_description_alter_watch_functions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="image",
            field=models.ImageField(upload_to=""),
        ),
    ]
