# Generated by Django 4.2.7 on 2023-11-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_watch_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="reference_number",
            field=models.CharField(max_length=200),
        ),
    ]
