# Generated by Django 4.2.7 on 2023-11-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_alter_watch_reference_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="availability",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="base_caliber",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bezel_material",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_color",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_material",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_diameter",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_material",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp_material",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="crystal",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial_numerals",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="lug_width",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement_caliber",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="watch",
            name="number_of_jewels",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="power_reserve",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="scope_of_delivery",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="thickness",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="watch",
            name="water_resistance",
            field=models.CharField(max_length=200),
        ),
    ]
