# Generated by Django 4.2.7 on 2023-11-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_watch_availability_alter_watch_base_caliber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watch",
            name="base_caliber",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="case_diameter",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="dealer_product_code",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="description",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="frequency",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="functions",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="location",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="lug_width",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="model",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="movement_caliber",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="number_of_jewels",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="power_reserve",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="reference_number",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="scope_of_delivery",
        ),
        migrations.RemoveField(
            model_name="watch",
            name="thickness",
        ),
        migrations.AddField(
            model_name="watch",
            name="band_color",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
