# Generated by Django 4.2.7 on 2023-11-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0015_remove_watch_base_caliber_remove_watch_case_diameter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="availability",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bezel_material",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_color",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="bracelet_material",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="brand",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="case_material",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="clasp_material",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="condition",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="crystal",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="dial_numerals",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="gender",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="watch",
            name="listing_code",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="movement",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="watch",
            name="water_resistance",
            field=models.CharField(max_length=300),
        ),
    ]
