# Generated by Django 4.2.7 on 2023-11-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_watch_availability_alter_watch_bezel_material_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="year_of_production",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
